config/routes.rb
Rails.application.routes.draw do
  resources :shows
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :season, optional: true
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :show, optional: true
  has_many :episodes
  accepts_nested_attributes_for :episodes
end

app/models/show.rb
class Show < ApplicationRecord
  has_many :seasons
  accepts_nested_attributes_for :seasons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: %i[ show edit update destroy ]

  # GET /shows or /shows.json
  def index
    @shows = Show.all
  end

  # GET /shows/1 or /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
    @show.seasons.build
         .episodes.build
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows or /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to show_url(@show), notice: "Show was successfully created." }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1 or /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to show_url(@show), notice: "Show was successfully updated." }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1 or /shows/1.json
  def destroy
    @show.destroy

    respond_to do |format|
      format.html { redirect_to shows_url, notice: "Show was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def show_params
      params.require(:show).permit(:name,
        seasons_attributes: [:number,
          episodes_attributes: [:title]
        ]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedForms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shows/_form.html.erb
<%= form_with(model: show, local: true) do |form| %>
  <% if show.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <%= form.fields_for :seasons do |s| %>
    <%= s.label :number %>
    <%= s.number_field :number %>    <%= s.fields_for :episodes do |e| %>
      <%= e.label :title %>
      <%= e.text_field :title %>
    <% end %>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/_show.html.erb
<div id="<%= dom_id show %>">
  <p>
    <strong>Name:</strong>
    <%= show.name %>
  </p>

</div>

app/views/shows/edit.html.erb
<h1>Editing show</h1>

<%= render "form", show: @show %>

<br>

<div>
  <%= link_to "Show this show", @show %> |
  <%= link_to "Back to shows", shows_path %>
</div>

app/views/shows/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shows</h1>

<div id="shows">
  <% @shows.each do |show| %>
    <%= render show %>
    <p>
      <%= link_to "Show this show", show %>
    </p>
  <% end %>
</div>

<%= link_to "New show", new_show_path %>

app/views/shows/new.html.erb
<h1>New show</h1>

<%= render "form", show: @show %>

<br>

<div>
  <%= link_to "Back to shows", shows_path %>
</div>

app/views/shows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @show %>

<div>
  <%= link_to "Edit this show", edit_show_path(@show) %> |
  <%= link_to "Back to shows", shows_path %>

  <%= button_to "Destroy this show", @show, method: :delete %>
</div>